export const ADDREVIEWER_REQUEST = "ADDREVIEWER_REQUEST";
export const INIT_LOGIN_REQUEST = "INIT_LOGIN_REQUEST";
export const ADDREVIEWER_SUCCESS = "ADDREVIEWER_SUCCESS";
export const ADDREVIEWER_REQUEST_FAIL = "ADDREVIEWER_REQUEST_FAIL";
