export const GET_VIDEO_REQUEST = "GET_VIDEO_REQUEST";
export const INIT_GET_VIDEO_REQUEST = "INIT_GET_VIDEO_REQUEST";
export const GET_VIDEO_SUCCESS = "GET_VIDEO_SUCCESS";
export const GET_VIDEO_REQUEST_FAIL = "GET_VIDEO_REQUEST_FAIL";
// update video reviewe
export const UPDATE_VIDEO_REQUEST = "UPDATE_VIDEO_REQUEST";
export const INIT_UPDATE_VIDEO_REQUEST = "INIT_UPDATE_VIDEO_REQUEST";
export const UPDATE_VIDEO_SUCCESS = "UPDATE_VIDEO_SUCCESS";
export const UPDATE_VIDEO_REQUEST_FAIL = "UPDATE_VIDEO_REQUEST_FAIL";
