//Video List
export const INIT_GET_VIDEO_LIST_REQUEST = "INIT_GET_VIDEO_LIST_REQUEST";
export const GET_VIDEO_LIST_REQUEST = "GET_VIDEO_LIST_REQUEST";
export const GET_VIDEO_LIST_SUCCESS = "GET_VIDEO_LIST_SUCCESS";
export const GET_VIDEO_LIST_REQUEST_FAIL = "GET_VIDEO_LIST_REQUEST_FAIL";
