export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const INIT_LOGIN_REQUEST = "INIT_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";
