export const GET_REVIEWERSTATUS_REQUEST = "GET_REVIEWERSTATUS_REQUEST";
export const INIT_GETREVIEWERSTATUS_REQUEST = "INIT_GETREVIEWERSTATUS_REQUEST";
export const GET_REVIEWERSTATUS_SUCCESS = "GET_REVIEWERSTATUS_SUCCESS";
export const GET_REVIEWERSTATUS_REQUEST_FAIL =
  "GET_REVIEWERSTATUS_REQUEST_FAIL";
